#!/bin/sh
#
#  Setup laptop/raspi for temporary mixmesh networking 
#  (ipv6/ipv4)
#
#    usage: mixnet-start wlan0
#
INTERFACE=$1
SSID="MIXMESH"
PASSWORD=off
CHANNEL=10
NMCLI=`which nmcli`

# 1. Ubuntu, we must stop nmcli
if [ -n "$NMCLI" ]; then
   sudo $NMCLI networking off
fi

sleep 3

# interface mac address
MACADDR=`ip link show $INTERFACE | grep ether | awk '{ print $2 }'`
# 40 random bits

GKEY=`date -u +"%s%N"`
EUI64=`ipv6calc --action geneui64 --in mac --out hex $MACADDR`
SHA=`echo $GKEY$EUI64 | sha1sum`

# 2. get mac address and generate a unique IPV6 "site" address

IFADDR=`ipv6calc --action prefixmac2ipv6 --in prefix+mac --out ipv6addr fd00:: $MACADDR`

# 3. setup interface

sudo ifconfig $INTERFACE down
sudo iwconfig $INTERFACE mode ad-hoc
sudo iwconfig $INTERFACE essid $SSID
sudo iwconfig $INTERFACE channel $CHANNEL
sudo iwconfig $INTERFACE key $PASSWORD 
sudo ifconfig $INTERFACE add $IFADDR/64
sudo ifconfig $INTERFACE up

# 4. run nodis with default routing support
#erl -detached -sname nodis -nodis device "\"$INTERFACE\"" family inet6 -s nodis
